var BOOKS = [
{
num:'1',
title:'Book 1: Debts and Lessons',
summary:'<strong>What I learned from the people who shaped me.</strong> Marcus opens not with philosophy but with gratitude. He lists the virtues he learned from his grandfather, parents, teachers, and mentors. From his grandfather Verus: good morals and the government of his temper. From his mother: piety, beneficence, and simplicity. From Rusticus: the idea that his character needed improvement. From Apollonius: freedom of will and steadiness of purpose. This book is a masterclass in learning from everyone around you.',
themes:'Gratitude, Mentorship, Character Formation, Humility',
passages:[
{id:'b1p1',text:'From my grandfather Verus I learned good morals and the government of my temper.',key:false},
{id:'b1p2',text:'From the reputation and remembrance of my father, modesty and a manly character.',key:false},
{id:'b1p3',text:'From my mother, piety and beneficence, and abstinence, not only from evil deeds, but even from evil thoughts; and further, simplicity in my way of living, far removed from the habits of the rich.',key:true,ex:'Marcus credits his mother for teaching him that goodness is not just about what you do, it is about what you think. You can avoid bad actions and still be toxic internally. True virtue means cleaning up your mental life too. And notice: she also taught him simplicity. The Emperor of Rome lived simply because his mother showed him that wealth and excess are not the point.'},
{id:'b1p4',text:'From my great-grandfather, not to have frequented public schools, and to have had good teachers at home, and to know that on such things a man should spend liberally.',key:false},
{id:'b1p5',text:'From my governor, to be neither of the green nor of the blue party at the games in the Circus, nor a partisan either of the Parmularius or the Scutarius at the gladiators\' fights; from him too I learned endurance of labour, and to want little, and to work with my own hands, and not to meddle with other people\'s affairs, and not to be ready to listen to slander.',key:false},
{id:'b1p6',text:'From Diognetus, not to busy myself about trifling things, and not to give credit to what was said by miracle-workers and jugglers about incantations and the driving away of daemons and such things.',key:false},
{id:'b1p7',text:'From Rusticus I received the impression that my character required improvement and discipline; and from him I learned not to be led astray to sophistic emulation, nor to writing on speculative matters, nor to delivering little hortatory orations, nor to showing myself off as a man who practises much discipline, or does benevolent acts in order to make a display.',key:true,ex:'This is about catching yourself performing virtue instead of actually being virtuous. Rusticus taught Marcus to stop showing off his discipline and his good deeds. If you are posting about your morning routine or your charity on social media, ask yourself: am I doing this for me, or for the audience? Real growth is invisible.'},
{id:'b1p8',text:'From Apollonius I learned freedom of will and undeviating steadiness of purpose; and to look to nothing else, not even for a moment, except to reason.',key:false},
{id:'b1p9',text:'From Sextus, a benevolent disposition, and the example of a family governed in a fatherly manner, and the idea of living conformably to nature; and gravity without affectation, and to look carefully after the interests of friends, and to tolerate ignorant persons, and those who form opinions without consideration.',key:false},
{id:'b1p10',text:'From Alexander the grammarian, to refrain from fault-finding, and not in a reproachful way to chide those who uttered any barbarous or solecistic or strange-sounding expression; but dexterously to introduce the very expression which ought to have been used, and in the way of answer or giving confirmation, or joining in an inquiry about the thing itself, not about the word, or by some other fit suggestion.',key:true,ex:'Do not correct people to make yourself feel smart. If someone uses the wrong word or makes a mistake, do not call them out. Instead, naturally use the correct version in your own speech. Let them learn by example, not by embarrassment. This is how a genuinely intelligent person operates: they make others feel smart, not stupid.'},
{id:'b1p11',text:'From Alexander the Platonic, not frequently nor without necessity to say to any one, or to write in a letter, that I have no leisure; nor continually to excuse the neglect of duties required by our relation to those with whom we live, by alleging urgent occupations.',key:false},
{id:'b1p12',text:'From Maximus I learned self-government, and not to be led aside by anything; and cheerfulness in all circumstances, as well as in illness; and a just admixture in the moral character of sweetness and dignity, and to do what was set before me without complaining.',key:false},
{id:'b1p13',text:'In my father I observed mildness of temper, and unchangeable resolution in the things which he had determined after due deliberation; and no vainglory in those things which men call honours; and a love of labour and perseverance; and a readiness to listen to those who had anything to propose for the common weal.',key:false},
{id:'b1p14',text:'From the gods I received that I had good grandfathers, good parents, a good sister, good teachers, good associates, good kinsmen and friends, nearly everything good. Further, I am thankful to the gods that I was not hurried into any offence against any of them, though I had a disposition which, if opportunity had offered, might have led me to do something of this kind; but, through their favour, there never was such a concurrence of circumstances as put me to the trial.',key:true,ex:'Even Marcus Aurelius admits he had a disposition that could have led him astray. He is not claiming to be naturally perfect. He is saying: I was lucky. I had the right people around me. I am grateful that life did not put me in circumstances where my worst impulses took over. That is radical honesty from the most powerful man alive. Nobody is inherently good; we are shaped by our circumstances and the people we are fortunate enough to learn from.'}
]
},
{
num:'2',
title:'Book 2: Written Among the Quadi',
summary:'<strong>On the front lines, writing to himself about mortality and duty.</strong> Marcus wrote this while commanding military campaigns on the Germanic frontier. The proximity to death sharpened his philosophy. He establishes core Stoic ideas: people will annoy you (expect it), time is a river sweeping everything away, your body is temporary, your fame is meaningless. What matters is living according to your rational nature, right now, in this moment.',
themes:'Mortality, Present Moment, Difficult People, Nature of Time',
passages:[
{id:'b2p1',text:'Begin each day by telling yourself: today I shall be meeting with interference, ingratitude, insolence, disloyalty, ill-will, and selfishness, all of them due to the offenders\' ignorance of what is good or evil.',key:true,ex:'Do not be surprised when people are difficult. Expect it. Not out of cynicism, but out of realism. People act badly because they do not know better, not because they are fundamentally evil. When you expect friction, it cannot ruin your day. And when you understand their behavior comes from ignorance, you can respond with patience instead of rage.'},
{id:'b2p2',text:'Since it is possible that thou mayest depart from life this very moment, regulate every act and thought accordingly.',key:true,ex:'You could die today. Not as a scary thought, but as a practical one. If this were your last day, would you spend it angry at that email? Would you hold that grudge? Would you postpone telling someone you love them? This is not morbid; it is the ultimate priority filter.'},
{id:'b2p3',text:'Do not act as if thou wert going to live ten thousand years. Death hangs over thee. While thou livest, while it is in thy power, be good.',key:true,ex:'Stop planning to be good "someday." You do not have ten thousand years. You might not have ten. The time to act with virtue is right now, this conversation, this decision, this moment. "While it is in thy power" is the key phrase. Your power is always and only in the present.'},
{id:'b2p4',text:'Let the part of thy soul which leads and governs be undisturbed by the movements in the flesh, whether of pleasure or of pain; and let it not unite with them, but let it circumscribe itself and limit those affects to their parts.',key:false},
{id:'b2p5',text:'How quickly all things disappear, in the universe the bodies themselves, but in time the remembrance of them; what is the nature of all sensible things, and particularly those which attract with the bait of pleasure or terrify by pain, or are noised abroad by vapoury fame; how worthless, and contemptible, and sordid, and perishable, and dead they are.',key:false},
{id:'b2p6',text:'Though thou shouldest be going to live three thousand years, and as many times ten thousand years, still remember that no man loses any other life than this which he now lives, nor lives any other than this which he now loses.',key:true,ex:'Whether you live 30 years or 3,000, the only thing you ever actually have is this present moment. The past is gone, the future is not here yet. Everyone, rich or poor, famous or unknown, owns the exact same amount of life: right now. That is the great equalizer.'},
{id:'b2p7',text:'It is in thy power whenever thou shalt choose to retire into thyself. For nowhere either with more quiet or more freedom from trouble does a man retire than into his own soul.',key:false},
{id:'b2p8',text:'Of human life the time is a point, and the substance is in a flux, and the perception dull, and the composition of the whole body subject to putrefaction, and the soul a whirl, and fortune hard to divine, and fame a thing devoid of judgement. And, to say all in a word, everything which belongs to the body is a stream, and what belongs to the soul is a dream and vapour, and life is a warfare and a stranger\'s sojourn, and after-fame is oblivion.',key:true,ex:'This is Marcus at his most raw. Life is a point in time. Your body is decaying. Your reputation means nothing. Everything is fleeting. He is not being nihilistic; he is clearing away illusions. When you stop chasing fame, comfort, and permanence, what is left? The only thing that endures: the quality of your character and your commitment to reason.'},
{id:'b2p9',text:'What then is that which is able to conduct a man? One thing and only one, philosophy. But this consists in keeping the daemon within a man free from violence and unharmed, superior to pains and pleasures, doing nothing without a purpose, nor yet falsely and with hypocrisy.',key:false}
]
},
{
num:'3',
title:'Book 3: Written in Carnuntum',
summary:'<strong>On the urgency of living well before time runs out.</strong> Written at the Roman military base in Carnuntum (modern Austria), this book intensifies the theme of mortality. Marcus reflects on how even great men like Hippocrates and Alexander the Great were swallowed by time. He urges himself to focus only on what is essential, to act with integrity, and to stop being distracted by what others think.',
themes:'Urgency, Simplicity, Integrity, Mortality of the Great',
passages:[
{id:'b3p1',text:'We ought to consider not only that our life is daily wasting away and a smaller part of it is left, but another thing also must be taken into the account, that if a man should live longer, it is quite uncertain whether the understanding will still continue sufficient for the comprehension of things.',key:false},
{id:'b3p2',text:'Hippocrates after curing many diseases himself fell sick and died. The Chaldaei foretold the deaths of many, and then fate caught them too. Alexander, and Pompeius, and Caius Caesar, after so often completely destroying whole cities, and in battle cutting to pieces many ten thousands of cavalry and infantry, themselves too at last departed from life.',key:true,ex:'The greatest doctor in history still got sick and died. The greatest conquerors still lost. Alexander ruled the known world and died at 32. This is not depressing; it is perspective. Whatever you are stressed about today, whatever feels impossibly important, remember: people who accomplished a thousand times more than you or I ever will were still erased by time. So stop taking yourself so seriously and just do good work.'},
{id:'b3p3',text:'Never value anything as profitable to thyself which shall compel thee to break thy promise, to lose thy self-respect, to hate any man, to suspect, to curse, to act the hypocrite, to desire anything that needs walls or curtains.',key:true,ex:'If getting something requires you to compromise who you are, it is not worth it. No amount of money, status, or success is profitable if the price is your integrity. If you have to hide what you are doing behind closed doors, that is your signal. The cost is always higher than it looks.'},
{id:'b3p4',text:'Do not waste the remainder of thy life in thoughts about others, when thou dost not refer thy thoughts to some object of common utility.',key:true,ex:'Stop thinking about what other people are doing. Every minute you spend wondering what someone else is up to, gossiping, or comparing yourself is a minute stolen from your own work and growth. Marcus literally calls it wandering away from your own ruling power. Your attention is your most valuable resource.'},
{id:'b3p5',text:'A man should use himself to think of those things only about which if one should suddenly ask, What hast thou now in thy thoughts? With perfect openness thou mightest immediately answer, This or That; so that from thy words it should be plain that everything in thee is simple and benevolent.',key:false},
{id:'b3p6',text:'Never esteem anything as of advantage to thee that shall make thee break thy word or lose thy self-respect.',key:false}
]
},
{
num:'4',
title:'Book 4: The Inner Citadel',
summary:'<strong>Your mind is an impregnable fortress, if you choose to make it one.</strong> Book 4 is the philosophical heart of the Meditations. Marcus develops his idea of the inner citadel: a place of retreat within your own mind where external chaos cannot reach. He explores how our judgments create our suffering, how fame is meaningless, and how time is a river that erases everything.',
themes:'Inner Peace, Judgement, Impermanence, The River of Time',
passages:[
{id:'b4p1',text:'Men seek retreats for themselves, houses in the country, sea-shores, and mountains; and thou too art wont to desire such things very much. But this is altogether a mark of the most common sort of men, for it is in thy power whenever thou shalt choose to retire into thyself. For nowhere either with more quiet or more freedom from trouble does a man retire than into his own soul.',key:true,ex:'You do not need a vacation, a cabin in the woods, or an escape from your life to find peace. The calm you are looking for already exists inside you. You can access it anytime by turning inward, not outward. External retreats are temporary. Internal calm is available 24/7, no ticket required.'},
{id:'b4p2',text:'Choose not to be harmed, and you will not feel harmed. Do not feel harmed, and you have not been.',key:true,ex:'Harm is a choice you make internally. If someone tries to embarrass you but you genuinely do not care, were you actually harmed? No. The moment you decide something cannot touch you, it cannot. Your reaction is what makes something an injury or a non-event.'},
{id:'b4p3',text:'Everything which happens either happens in such wise as thou art formed by nature to bear it, or as thou art not formed by nature to bear it.',key:false},
{id:'b4p4',text:'Time is like a river made up of the events which happen, and a violent stream; for as soon as a thing has been seen, it is carried away, and another comes in its place, and this will be carried away too.',key:true,ex:'Every moment you are living right now is already becoming the past. You cannot grab time and hold it. The meeting you had yesterday, the argument from last week: already swept downstream. If everything passes anyway, why cling to the bad stuff? Let the river carry it.'},
{id:'b4p5',text:'Nothing happens to any man which he is not formed by nature to bear.',key:false},
{id:'b4p6',text:'It is in thy power to live free from all compulsion in the greatest tranquility of mind, even if all the world cry out against thee as much as they choose.',key:false},
{id:'b4p7',text:'Everything which is in any way beautiful is beautiful in itself, and terminates in itself, not having praise as part of itself. Neither worse then nor better is a thing made by being praised.',key:true,ex:'Real beauty, real quality, real goodness does not need applause. A sunset is not better because someone Instagrammed it. Your work is not better because it got likes. Things that are genuinely good are good whether anyone notices or not. If you need external validation to feel like something has value, you are not evaluating the thing; you are evaluating your need for approval.'},
{id:'b4p8',text:'How much trouble he avoids who does not look to see what his neighbour says or does or thinks, but only to what he does himself, that it may be just and pure.',key:false},
{id:'b4p9',text:'A man should be upright, not be kept upright.',key:false},
{id:'b4p10',text:'Asia, Europe are corners of the world; all the sea a drop in the world; Athos a little clod of the world; all the present time is a point in eternity. All things are little, changeable, perishable.',key:false},
{id:'b4p11',text:'Remember that all is opinion.',key:false}
]
},
{
num:'5',
title:'Book 5: On Getting Out of Bed',
summary:'<strong>The daily battle between comfort and purpose.</strong> Book 5 opens with one of the most famous passages in philosophy: Marcus arguing with himself about getting out of bed. From there, he explores the idea that we were born for a purpose, that nature has a design, and that complaining about what happens to us is absurd because everything is interconnected.',
themes:'Purpose, Duty, Overcoming Resistance, Obstacles as Opportunity',
passages:[
{id:'b5p1',text:'In the morning when thou risest unwillingly, let this thought be present: I am rising to the work of a human being. Why then am I dissatisfied if I am going to do the things for which I exist and for which I was brought into the world? Or have I been made for this, to lie in the bed-clothes and keep myself warm?',key:true,ex:'Marcus Aurelius, the most powerful man in the world, still struggled to get out of bed. His answer? You were not born to be comfortable. You were born to contribute. When that alarm goes off and every part of you wants to stay in bed, remember: the work you do is the point of being alive. Comfort is not your purpose.'},
{id:'b5p2',text:'But it is more pleasant. Dost thou exist then to take thy pleasure, and not at all for action or exertion? Dost thou not see the little plants, the little birds, the ants, the spiders, the bees working together to put in order their several parts of the universe?',key:false},
{id:'b5p3',text:'The soul becomes dyed with the colour of its thoughts.',key:true,ex:'Whatever you think about all day is what you become. If you constantly run negative, anxious thoughts, your entire personality takes on that shade. Think with clarity, gratitude, and purpose, and your character reflects that instead. You are literally painting yourself with your thoughts, one at a time.'},
{id:'b5p4',text:'The impediment to action advances action. What stands in the way becomes the way.',key:true,ex:'This is the most famous Stoic idea, later popularized as "the obstacle is the way." Every problem you face is not blocking you from your path; it IS your path. Got rejected by a client? That teaches you to pitch better. Lost money? That teaches you risk management. The obstacle is not separate from your growth. It is the material your growth is made of.'},
{id:'b5p5',text:'Do not think that what is hard for thee to master is impossible for man; but if a thing is possible and proper to man, deem it attainable by thee.',key:true,ex:'If any human being has ever done it, you can learn to do it too. Not necessarily at the same level, but the capacity exists in you. This eliminates "I am just not the type" excuses. You are the human type. That is enough.'},
{id:'b5p6',text:'If any man is able to convince me and show me that I do not think or act right, I will gladly change; for I seek the truth, by which no man was ever injured. But he is injured who abides in his error and ignorance.',key:false},
{id:'b5p7',text:'In the gymnastic exercises suppose that a man has torn thee with his nails, and by dashing against thy head has inflicted a wound. Well, we neither show any signs of vexation, nor are we offended, nor do we suspect him afterwards as a treacherous fellow.',key:false}
]
},
{
num:'6',
title:'Book 6: On Power and Perspective',
summary:'<strong>How to wield power without losing yourself.</strong> Marcus reflects on the responsibilities of leadership and how easily power corrupts. He reminds himself that even emperors are temporary, that revenge is beneath a rational person, and that the best way to deal with enemies is simply not to become like them.',
themes:'Leadership, Self-Control, Revenge, Power Over Mind',
passages:[
{id:'b6p1',text:'The best revenge is not to be like your enemy.',key:true,ex:'When someone wrongs you, the temptation is to get back at them, to become just as petty or cruel. But that is the real loss: becoming the thing you hate. The most powerful response is to stay exactly who you are. Let them be small. You be better. That asymmetry is the real victory.'},
{id:'b6p2',text:'You have power over your mind, not outside events. Realize this, and you will find strength.',key:true,ex:'You cannot control what happens to you, but you can always control how you respond. The weather, other people\'s behaviour, the economy: none of that is up to you. Your thoughts and reactions? Those are yours. When you stop wasting energy on things outside your control and pour it into what IS within your control, that is where real strength comes from.'},
{id:'b6p3',text:'How much more grievous are the consequences of anger than the causes of it.',key:true,ex:'Think about the last time you got angry. What did the anger actually cost you? Probably more than the thing that triggered it. You said something you regret, ruined a relationship, stressed your body, wasted hours fuming. The original problem was small. Your anger made it enormous.'},
{id:'b6p4',text:'Accept the things to which fate binds you, and love the people with whom fate brings you together, and do so with all your heart.',key:true,ex:'Stop fighting your circumstances. You were dealt this hand, these relationships, this life. Instead of wishing for different cards, play the ones you have with everything you have got. The people around you right now? Love them fully. The situation you are in? Work with it, not against it.'},
{id:'b6p5',text:'The happiness of your life depends upon the quality of your thoughts: therefore, guard accordingly, and take care that you entertain no notions unsuitable to virtue and reasonable nature.',key:false},
{id:'b6p6',text:'Loss is nothing else but change, and change is Nature\'s delight.',key:false},
{id:'b6p7',text:'That which is not good for the bee-hive cannot be good for the bee.',key:false},
{id:'b6p8',text:'Look within. Within is the fountain of good, and it will ever bubble up, if thou wilt ever dig.',key:false}
]
},
{
num:'7',
title:'Book 7: On Pain, Endurance, and Beauty',
summary:'<strong>How to endure suffering and still see the beauty in life.</strong> Book 7 is about resilience. Marcus confronts pain, suffering, and the temptation to give up. He reminds himself that pain is temporary, that his judgments about pain make it worse than the pain itself, and that even in difficulty, there is beauty to be found.',
themes:'Endurance, Beauty, Pain Management, Second Life',
passages:[
{id:'b7p1',text:'Think of yourself as dead. You have lived your life. Now take what\'s left and live it properly.',key:true,ex:'Imagine you already died, and everything from this point forward is bonus time. How would you spend it? Probably not scrolling your phone or holding grudges. This mental trick kills procrastination and pettiness in one shot. You got a second chance. Do not waste this one either.'},
{id:'b7p2',text:'Dwell on the beauty of life. Watch the stars, and see yourself running with them.',key:true,ex:'Do not get so lost in problems, deadlines, and worries that you forget to notice the actual world around you. The stars have been doing their thing for billions of years. You are part of that same cosmic show, not separate from it. Taking that wider view makes your daily anxieties feel appropriately small.'},
{id:'b7p3',text:'Very little is needed to make a happy life; it is all within yourself, in your way of thinking.',key:true,ex:'Happiness is not about getting more. It is about needing less. And even needing less is just a thought pattern. Adjust how you think, and your entire experience of life changes. The richest person in the world with a miserable mindset is poorer than someone content with very little.'},
{id:'b7p4',text:'The art of living is more like wrestling than dancing, in so far as it stands ready against the accidental and the unforeseen, and is not apt to fall.',key:false},
{id:'b7p5',text:'When you arise in the morning, think of what a precious privilege it is to be alive, to breathe, to think, to enjoy, to love.',key:true,ex:'Before you check your phone, before you think about your problems, before you do anything: recognize that being alive at all is extraordinary. Billions of years of cosmic accidents led to you being here, conscious, breathing. Starting the day from gratitude instead of anxiety changes everything downstream.'},
{id:'b7p6',text:'How ridiculous and how strange to be surprised at anything which happens in life!',key:false},
{id:'b7p7',text:'Receive without conceit, release without struggle.',key:false},
{id:'b7p8',text:'Each thing is of like form from everlasting and comes round again in its cycle.',key:false}
]
},
{
num:'8',
title:'Book 8: On Judgments and Disturbance',
summary:'<strong>Your suffering is created by your own judgments, not by events.</strong> Book 8 deepens the insight that it is never the situation that disturbs you, only your interpretation of it. Marcus applies this to insults, losses, physical pain, and political frustration. This book is essentially a manual for emotional regulation, written 2,000 years before cognitive behavioral therapy formalized the same ideas.',
themes:'Cognitive Reframing, Emotional Control, Self-Caused Suffering',
passages:[
{id:'b8p1',text:'If you are distressed by anything external, the pain is not due to the thing itself, but to your estimate of it; and this you have the power to revoke at any moment.',key:true,ex:'Nothing outside of you has the power to hurt you emotionally on its own. It is your interpretation of the event that causes the pain. Someone insults you? The words are not what hurt. It is the story you tell yourself about what those words mean. And since you wrote that story, you can rewrite it whenever you want.'},
{id:'b8p2',text:'Remember that it is not he who gives abuse or blows who affronts, but the view we take of these things as insulting. When therefore any one provokes you, be assured that it is your own opinion which provokes you.',key:false},
{id:'b8p3',text:'Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.',key:true,ex:'This is arguably the most important sentence in the entire book. Every piece of information you receive has been filtered through someone\'s biases, experiences, and agenda. The news, your friend\'s advice, your own interpretation of events: all opinions. All perspectives. Treating any of them as absolute truth is where mistakes begin. Hold everything loosely.'},
{id:'b8p4',text:'Today I escaped anxiety. Or no, I discarded it, because it was within me, in my own perceptions, not outside.',key:true,ex:'Notice the self-correction: he does not say he escaped anxiety, as if it were chasing him. He says he discarded it, because it was never external. It was something he was carrying by choice. Anxiety is not something that happens to you. It is something you do. And what you do, you can stop doing.'},
{id:'b8p5',text:'Look back over the past, with its changing empires that rose and fell, and you can foresee the future too.',key:false},
{id:'b8p6',text:'Be like the cliff against which the waves continually break; but it stands firm, and tames the fury of the water around it.',key:true,ex:'When life hits you repeatedly, when problems keep coming and people keep pushing, do not try to fight every wave. Just stand. The cliff does not move. It does not argue with the ocean. It just exists with such firmness that the chaos exhausts itself. That is the posture: not aggressive resistance, but immovable presence.'}
]
},
{
num:'9',
title:'Book 9: On Wrongdoing and Forgiveness',
summary:'<strong>People who wrong you are ignorant, not evil.</strong> Book 9 tackles the hardest Stoic practice: forgiving people who hurt you. Marcus\'s approach is analytical: people who do wrong do not understand what they are doing. They are making an error of judgment, not committing deliberate evil. Understanding this makes forgiveness rational, not just virtuous.',
themes:'Forgiveness, Self-Reflection, Human Nature, Injustice',
passages:[
{id:'b9p1',text:'He who does wrong does wrong against himself. He who acts unjustly acts unjustly to himself, because he makes himself bad.',key:true,ex:'When someone lies, cheats, or acts cruelly, the primary victim is actually themselves. They are corroding their own character. They have to live inside a mind that chose dishonesty. You get to walk away. They do not. This reframe does not excuse their behavior, but it does explain why revenge is unnecessary. They are already punishing themselves.'},
{id:'b9p2',text:'When you are offended at any man\'s fault, immediately turn to yourself and reflect in what manner you yourself have erred.',key:true,ex:'Before you judge someone, check yourself. You have probably done the same thing, or something worse, in a different context. This is not about guilt; it is about humility. It is much harder to stay angry at someone\'s flaw when you recognize the same flaw living inside yourself.'},
{id:'b9p3',text:'How strangely men act. They will not praise those who are living at the same time and living with themselves; but to be themselves praised by posterity, by those whom they have never seen or ever will see, this they set much value on.',key:false},
{id:'b9p4',text:'Do not despise death, but be well content with it, since this too is one of those things which nature wills.',key:false},
{id:'b9p5',text:'Adapt thyself to the things among which thy lot has been cast; and the men among whom thou hast received thy portion, these love sincerely.',key:false}
]
},
{
num:'10',
title:'Book 10: On Action Over Theory',
summary:'<strong>Stop talking about virtue. Start practicing it.</strong> By Book 10, Marcus is done with theory. He is frustrated with himself for knowing the right principles but not always living them. This book is about closing the gap between knowing and doing.',
themes:'Action, Simplicity, Practice Over Theory, Acceptance',
passages:[
{id:'b10p1',text:'Waste no more time arguing about what a good man should be. Be one.',key:true,ex:'Stop debating, reading about, or planning to be better. Just act. Every minute you spend theorizing about virtue is a minute you could have spent practicing it. Goodness is not a concept to understand. It is a thing to do. Starting right now, not after one more book.'},
{id:'b10p2',text:'Consider that everything is opinion, and opinion is in thy power. Take away then, when thou choosest, thy opinion, and like a mariner who has doubled the promontory, thou wilt find calm, total tranquility, and a waveless bay.',key:false},
{id:'b10p3',text:'Do not then consider life a thing of any value. For look at the immensity of time behind thee, and to the time which is before thee, another boundless space.',key:false},
{id:'b10p4',text:'Always run to the short way; and the short way is the natural: accordingly say and do everything in conformity with the soundest reason.',key:false},
{id:'b10p5',text:'No longer talk at all about the kind of man that a good man ought to be, but be such.',key:false},
{id:'b10p6',text:'He who fears death either fears the loss of sensation or a different kind of sensation. But if thou shalt have no sensation, neither wilt thou feel any harm.',key:false}
]
},
{
num:'11',
title:'Book 11: On the Rational Soul',
summary:'<strong>The properties of a rational soul and how to protect yours.</strong> Book 11 is a meditation on what makes the human mind special and how easily we corrupt it. Marcus lists the properties of a well-functioning rational soul and deals with anger at length, arguing that anger is never useful and always a sign that you have forgotten your principles.',
themes:'Rational Nature, Anger Management, Self-Governance',
passages:[
{id:'b11p1',text:'The properties of the rational soul: it sees itself, analyses itself, and makes itself such as it chooses; the fruit which it bears itself enjoys.',key:false},
{id:'b11p2',text:'It is peculiar to man to love even those who do wrong. And this happens, if when they do wrong it occurs to thee that they are kinsmen, and that they do wrong through ignorance and unintentionally, and that soon both of you will die; and above all, that the wrongdoer has done thee no harm, for he has not made thy ruling faculty worse than it was before.',key:true,ex:'The highest form of love is loving people who mess up. How? By remembering three things: they are human like you, they did not know better, and you are both going to die soon anyway. Most importantly, they have not actually damaged the real you. Your character, your inner life, your soul: those are untouched. Only you can damage those.'},
{id:'b11p3',text:'Persuade me or prove to me that I am wrong in thought or deed, and I will gladly change. For I seek the truth, which has never yet harmed anyone. It is only persistence in self-delusion and ignorance which does harm.',key:true,ex:'Imagine if everyone operated this way. "Show me I am wrong and I will thank you for it." Most people defend their opinions like territory. Marcus says: my opinions are not me. If they are wrong, replacing them makes me better, not weaker. Truth never harms. Only stubbornly clinging to comfortable lies does.'},
{id:'b11p4',text:'The soul of man does violence to itself, first of all, when it becomes an abscess and, as it were, a tumour on the universe, so far as it can. For to be vexed at anything which happens is a separation of ourselves from nature.',key:false},
{id:'b11p5',text:'How cruel it is not to allow men to strive after the things which appear to them to be suitable to their nature and profitable! And yet in a manner thou dost not allow them to do this, when thou art vexed because they do wrong.',key:false}
]
},
{
num:'12',
title:'Book 12: Final Reflections',
summary:'<strong>The last words of an emperor to himself.</strong> Book 12 reads like Marcus is summing up everything he has learned, perhaps sensing his time is short. The themes are distilled to their essence: do not fear death, live according to nature, remember that everything is temporary, and focus on what you can control. There is a sense of acceptance and peace here that the earlier books do not quite have.',
themes:'Death, Legacy, Final Wisdom, Acceptance, Nature',
passages:[
{id:'b12p1',text:'All those things at which thou wishest to arrive by a circuitous road, thou canst have now, if thou dost not refuse them to thyself.',key:false},
{id:'b12p2',text:'It is not death that a man should fear, but he should fear never beginning to live.',key:true,ex:'Death is not the tragedy. The tragedy is reaching the end and realizing you never actually started living. You played it safe, waited for the right moment, followed someone else\'s script. The real fear is not that life will end. It is that it will end before you have done anything real with it.'},
{id:'b12p3',text:'How small a part of the boundless and unfathomable time is assigned to every man! For it is very soon swallowed up in the eternal.',key:false},
{id:'b12p4',text:'Soon, very soon, thou wilt be ashes, or a skeleton, and either a name or not even a name; but name is sound and echo. And the things which are much valued in life are empty and rotten and trifling.',key:true,ex:'You are going to be forgotten. Your name, your achievements, your social media following: all of it turns to dust. Marcus is not being bleak; he is being practical. If none of it lasts, then chasing status and material things is a waste of the little time you have. What is left when you strip all that away? How you treated people and whether you lived with integrity.'},
{id:'b12p5',text:'The object of life is not to be on the side of the majority, but to escape finding oneself in the ranks of the insane.',key:true,ex:'Just because everyone is doing something does not make it right. Consensus is not a measure of truth. If the majority is chasing status, numbing themselves with entertainment, and avoiding hard truths, joining them does not make you sane. It makes you comfortable. True sanity is thinking for yourself, even when that means standing alone.'},
{id:'b12p6',text:'Pass then through this little space of time conformably to nature, and end thy journey in content, just as an olive falls off when it is ripe, blessing nature who produced it, and thanking the tree on which it grew.',key:true,ex:'This is how Marcus envisions a good death: naturally, gently, with gratitude. Like a ripe olive falling from its tree, not clinging, not resisting, just ready. Live according to your nature, do your work, love the people around you, and when it is time to go, go with the same grace. No drama. No regret. Just: thank you for the tree.'},
{id:'b12p7',text:'Do every act of thy life as if it were the last.',key:false}
]
}
];
